from __future__ import annotations

from enum import StrEnum


class MarketRegime(StrEnum):
    GREEN = "GREEN"
    YELLOW = "YELLOW"
    RED = "RED"


class SignalGrade(StrEnum):
    S = "S"
    A = "A"
    B = "B"
    WATCH = "WATCH"
    NO_TRADE = "NO_TRADE"


class DecisionType(StrEnum):
    NO_ACTION = "NO_ACTION"
    FIRST_ENTRY_CANDIDATE = "FIRST_ENTRY_CANDIDATE"
    ADD_ENTRY_CANDIDATE = "ADD_ENTRY_CANDIDATE"
    REBUY_CANDIDATE = "REBUY_CANDIDATE"
    RISK_REVIEW = "RISK_REVIEW"


class PositionState(StrEnum):
    EMPTY = "EMPTY"
    WAITING_1ST_APPROVAL = "WAITING_1ST_APPROVAL"
    WAITING_1ST_FILL = "WAITING_1ST_FILL"
    HOLDING_1ST = "HOLDING_1ST"
    WAITING_2ND_APPROVAL = "WAITING_2ND_APPROVAL"
    WAITING_2ND_FILL = "WAITING_2ND_FILL"
    HOLDING_2ND = "HOLDING_2ND"
    WAITING_3RD_APPROVAL = "WAITING_3RD_APPROVAL"
    WAITING_3RD_FILL = "WAITING_3RD_FILL"
    HOLDING_3RD = "HOLDING_3RD"
    WAITING_4TH_APPROVAL = "WAITING_4TH_APPROVAL"
    WAITING_4TH_FILL = "WAITING_4TH_FILL"
    HOLDING_4TH = "HOLDING_4TH"
    PARTIAL_TP_1 = "PARTIAL_TP_1"
    WAITING_REBUY_APPROVAL = "WAITING_REBUY_APPROVAL"
    WAITING_REBUY_FILL = "WAITING_REBUY_FILL"
    HOLDING_REBUY = "HOLDING_REBUY"
    COOLDOWN = "COOLDOWN"
    SAFE_MODE = "SAFE_MODE"


class OrderPurpose(StrEnum):
    ENTRY_1 = "ENTRY_1"
    ENTRY_2 = "ENTRY_2"
    ENTRY_3 = "ENTRY_3"
    ENTRY_4 = "ENTRY_4"
    REBUY = "REBUY"
    TP1 = "TP1"
    TP2 = "TP2"
    PANIC = "PANIC"


class OrderStatus(StrEnum):
    CREATED = "CREATED"
    SUBMITTED = "SUBMITTED"
    OPEN = "OPEN"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"
    UNKNOWN = "UNKNOWN"


class RiskReviewLevel(StrEnum):
    NONE = "NONE"
    INFO = "INFO"
    REVIEW = "REVIEW"
    HIGH = "HIGH"


class ApprovalStage(StrEnum):
    REVIEW = "REVIEW"
    EXECUTION = "EXECUTION"
